apiVersion: apps/v1
kind: Deployment
metadata:
  name: idowu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idowu
  template:
    metadata:
      name: idowu
      labels:
        app: idowu
    spec:
      containers:
      - name: nginx
        image: idowudevops/nginx
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: idowu
spec:
  selector:
    app: idowu
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
